SEED: 100

BACKBONE: 'GCN' # ['GCN', 'GAT', 'GIN']
SPLIT: 'random' # ['random', 'scaffold']

DATASET: 'freesolv' # ['freesolv', 'esol', 'scgas', 'solubility']

BATCH_SIZE: 32
MAX_EPOCHS: 300
K: 5

R_HOME: 'C:\R-4.4.2' # Specify your path of 'R'